mkdir data/gittables/unzipped

unzip -q data/gittables/src_zip/abstraction_tables_licensed.zip -d data/gittables/unzipped/abstraction_tables_licensed
unzip -q data/gittables/src_zip/allegro_con_spirito_tables_licensed.zip -d data/gittables/unzipped/allegro_con_spirito_tables_licensed
unzip -q data/gittables/src_zip/attrition_rate_tables_licensed.zip -d data/gittables/unzipped/attrition_rate_tables_licensed
unzip -q data/gittables/src_zip/beats_per_minute_tables_licensed.zip -d data/gittables/unzipped/beats_per_minute_tables_licensed
unzip -q data/gittables/src_zip/beauty_sleep_tables_licensed.zip -d data/gittables/unzipped/beauty_sleep_tables_licensed
unzip -q data/gittables/src_zip/bits_per_second_tables_licensed.zip -d data/gittables/unzipped/bits_per_second_tables_licensed
unzip -q data/gittables/src_zip/cardiac_output_tables_licensed.zip -d data/gittables/unzipped/cardiac_output_tables_licensed
unzip -q data/gittables/src_zip/cease_tables_licensed.zip -d data/gittables/unzipped/cease_tables_licensed
unzip -q data/gittables/src_zip/centripetal_acceleration_tables_licensed.zip -d data/gittables/unzipped/centripetal_acceleration_tables_licensed
unzip -q data/gittables/src_zip/channel_capacity_tables_licensed.zip -d data/gittables/unzipped/channel_capacity_tables_licensed
unzip -q data/gittables/src_zip/clotting_time_tables_licensed.zip -d data/gittables/unzipped/clotting_time_tables_licensed
unzip -q data/gittables/src_zip/command_processing_overhead_time_tables_licensed.zip -d data/gittables/unzipped/command_processing_overhead_time_tables_licensed
unzip -q data/gittables/src_zip/count_per_minute_tables_licensed.zip -d data/gittables/unzipped/count_per_minute_tables_licensed
unzip -q data/gittables/src_zip/crime_rate_tables_licensed.zip -d data/gittables/unzipped/crime_rate_tables_licensed
unzip -q data/gittables/src_zip/data_rate_tables_licensed.zip -d data/gittables/unzipped/data_rate_tables_licensed
unzip -q data/gittables/src_zip/dead_air_tables_licensed.zip -d data/gittables/unzipped/dead_air_tables_licensed
unzip -q data/gittables/src_zip/dogwatch_tables_licensed.zip -d data/gittables/unzipped/dogwatch_tables_licensed
unzip -q data/gittables/src_zip/dose_rate_tables_licensed.zip -d data/gittables/unzipped/dose_rate_tables_licensed
unzip -q data/gittables/src_zip/dwarf_tables_licensed.zip -d data/gittables/unzipped/dwarf_tables_licensed
unzip -q data/gittables/src_zip/entr_acte_tables_licensed.zip -d data/gittables/unzipped/entr_acte_tables_licensed
unzip -q data/gittables/src_zip/episcopate_tables_licensed.zip -d data/gittables/unzipped/episcopate_tables_licensed
unzip -q data/gittables/src_zip/erythrocyte_sedimentation_rate_tables_licensed.zip -d data/gittables/unzipped/erythrocyte_sedimentation_rate_tables_licensed
unzip -q data/gittables/src_zip/escape_velocity_tables_licensed.zip -d data/gittables/unzipped/escape_velocity_tables_licensed
unzip -q data/gittables/src_zip/fertile_period_tables_licensed.zip -d data/gittables/unzipped/fertile_period_tables_licensed
unzip -q data/gittables/src_zip/graveyard_watch_tables_licensed.zip -d data/gittables/unzipped/graveyard_watch_tables_licensed
unzip -q data/gittables/src_zip/growth_rate_tables_licensed.zip -d data/gittables/unzipped/growth_rate_tables_licensed
unzip -q data/gittables/src_zip/half_life_tables_licensed.zip -d data/gittables/unzipped/half_life_tables_licensed
unzip -q data/gittables/src_zip/halftime_tables_licensed.zip -d data/gittables/unzipped/halftime_tables_licensed
unzip -q data/gittables/src_zip/heterotroph_tables_licensed.zip -d data/gittables/unzipped/heterotroph_tables_licensed
unzip -q data/gittables/src_zip/hypervelocity_tables_licensed.zip -d data/gittables/unzipped/hypervelocity_tables_licensed
unzip -q data/gittables/src_zip/id_tables_licensed.zip -d data/gittables/unzipped/id_tables_licensed
unzip -q data/gittables/src_zip/incubation_period_tables_licensed.zip -d data/gittables/unzipped/incubation_period_tables_licensed
unzip -q data/gittables/src_zip/indiction_tables_licensed.zip -d data/gittables/unzipped/indiction_tables_licensed
unzip -q data/gittables/src_zip/inflation_rate_tables_licensed.zip -d data/gittables/unzipped/inflation_rate_tables_licensed
unzip -q data/gittables/src_zip/interim_tables_licensed.zip -d data/gittables/unzipped/interim_tables_licensed
unzip -q data/gittables/src_zip/in_time_tables_licensed.zip -d data/gittables/unzipped/in_time_tables_licensed
unzip -q data/gittables/src_zip/kilohertz_tables_licensed.zip -d data/gittables/unzipped/kilohertz_tables_licensed
unzip -q data/gittables/src_zip/kilometers_per_hour_tables_licensed.zip -d data/gittables/unzipped/kilometers_per_hour_tables_licensed
unzip -q data/gittables/src_zip/lapse_tables_licensed.zip -d data/gittables/unzipped/lapse_tables_licensed
unzip -q data/gittables/src_zip/last_gasp_tables_licensed.zip -d data/gittables/unzipped/last_gasp_tables_licensed
unzip -q data/gittables/src_zip/latent_period_tables_licensed.zip -d data/gittables/unzipped/latent_period_tables_licensed
unzip -q data/gittables/src_zip/lead_time_tables_licensed.zip -d data/gittables/unzipped/lead_time_tables_licensed
unzip -q data/gittables/src_zip/living_thing_tables_licensed.zip -d data/gittables/unzipped/living_thing_tables_licensed
unzip -q data/gittables/src_zip/lunitidal_interval_tables_licensed.zip -d data/gittables/unzipped/lunitidal_interval_tables_licensed
unzip -q data/gittables/src_zip/meno_mosso_tables_licensed.zip -d data/gittables/unzipped/meno_mosso_tables_licensed
unzip -q data/gittables/src_zip/menstrual_cycle_tables_licensed.zip -d data/gittables/unzipped/menstrual_cycle_tables_licensed
unzip -q data/gittables/src_zip/metabolic_rate_tables_licensed.zip -d data/gittables/unzipped/metabolic_rate_tables_licensed
unzip -q data/gittables/src_zip/miles_per_hour_tables_licensed.zip -d data/gittables/unzipped/miles_per_hour_tables_licensed
unzip -q data/gittables/src_zip/multistage_tables_licensed.zip -d data/gittables/unzipped/multistage_tables_licensed
unzip -q data/gittables/src_zip/musth_tables_licensed.zip -d data/gittables/unzipped/musth_tables_licensed
unzip -q data/gittables/src_zip/neonatal_mortality_tables_licensed.zip -d data/gittables/unzipped/neonatal_mortality_tables_licensed
unzip -q data/gittables/src_zip/object_tables_licensed.zip -d data/gittables/unzipped/object_tables_licensed
unzip -q data/gittables/src_zip/orbit_period_tables_licensed.zip -d data/gittables/unzipped/orbit_period_tables_licensed
unzip -q data/gittables/src_zip/organism_tables_licensed.zip -d data/gittables/unzipped/organism_tables_licensed
unzip -q data/gittables/src_zip/parent_tables_licensed.zip -d data/gittables/unzipped/parent_tables_licensed
unzip -q data/gittables/src_zip/peacetime_tables_licensed.zip -d data/gittables/unzipped/peacetime_tables_licensed
unzip -q data/gittables/src_zip/peculiar_velocity_tables_licensed.zip -d data/gittables/unzipped/peculiar_velocity_tables_licensed
unzip -q data/gittables/src_zip/physical_entity_tables_licensed.zip -d data/gittables/unzipped/physical_entity_tables_licensed
unzip -q data/gittables/src_zip/processing_time_tables_licensed.zip -d data/gittables/unzipped/processing_time_tables_licensed
unzip -q data/gittables/src_zip/question_time_tables_licensed.zip -d data/gittables/unzipped/question_time_tables_licensed
unzip -q data/gittables/src_zip/quick_time_tables_licensed.zip -d data/gittables/unzipped/quick_time_tables_licensed
unzip -q data/gittables/src_zip/radial_pulse_tables_licensed.zip -d data/gittables/unzipped/radial_pulse_tables_licensed
unzip -q data/gittables/src_zip/radial_velocity_tables_licensed.zip -d data/gittables/unzipped/radial_velocity_tables_licensed
unzip -q data/gittables/src_zip/rainy_day_tables_licensed.zip -d data/gittables/unzipped/rainy_day_tables_licensed
unzip -q data/gittables/src_zip/rate_of_return_tables_licensed.zip -d data/gittables/unzipped/rate_of_return_tables_licensed
unzip -q data/gittables/src_zip/reaction_time_tables_licensed.zip -d data/gittables/unzipped/reaction_time_tables_licensed
unzip -q data/gittables/src_zip/real_time_tables_licensed.zip -d data/gittables/unzipped/real_time_tables_licensed
unzip -q data/gittables/src_zip/relaxation_time_tables_licensed.zip -d data/gittables/unzipped/relaxation_time_tables_licensed
unzip -q data/gittables/src_zip/respiratory_rate_tables_licensed.zip -d data/gittables/unzipped/respiratory_rate_tables_licensed
unzip -q data/gittables/src_zip/return_on_invested_capital_tables_licensed.zip -d data/gittables/unzipped/return_on_invested_capital_tables_licensed
unzip -q data/gittables/src_zip/revolutions_per_minute_tables_licensed.zip -d data/gittables/unzipped/revolutions_per_minute_tables_licensed
unzip -q data/gittables/src_zip/rotational_latency_tables_licensed.zip -d data/gittables/unzipped/rotational_latency_tables_licensed
unzip -q data/gittables/src_zip/running_time_tables_licensed.zip -d data/gittables/unzipped/running_time_tables_licensed
unzip -q data/gittables/src_zip/safe_period_tables_licensed.zip -d data/gittables/unzipped/safe_period_tables_licensed
unzip -q data/gittables/src_zip/sampling_frequency_tables_licensed.zip -d data/gittables/unzipped/sampling_frequency_tables_licensed
unzip -q data/gittables/src_zip/sampling_rate_tables_licensed.zip -d data/gittables/unzipped/sampling_rate_tables_licensed
unzip -q data/gittables/src_zip/secretory_phase_tables_licensed.zip -d data/gittables/unzipped/secretory_phase_tables_licensed
unzip -q data/gittables/src_zip/seek_time_tables_licensed.zip -d data/gittables/unzipped/seek_time_tables_licensed
unzip -q data/gittables/src_zip/shiva_tables_licensed.zip -d data/gittables/unzipped/shiva_tables_licensed
unzip -q data/gittables/src_zip/show_time_tables_licensed.zip -d data/gittables/unzipped/show_time_tables_licensed
unzip -q data/gittables/src_zip/solar_constant_tables_licensed.zip -d data/gittables/unzipped/solar_constant_tables_licensed
unzip -q data/gittables/src_zip/speed_of_light_tables_licensed.zip -d data/gittables/unzipped/speed_of_light_tables_licensed
unzip -q data/gittables/src_zip/split_shift_tables_licensed.zip -d data/gittables/unzipped/split_shift_tables_licensed
unzip -q data/gittables/src_zip/steerageway_tables_licensed.zip -d data/gittables/unzipped/steerageway_tables_licensed
unzip -q data/gittables/src_zip/stopping_point_tables_licensed.zip -d data/gittables/unzipped/stopping_point_tables_licensed
unzip -q data/gittables/src_zip/terminal_velocity_tables_licensed.zip -d data/gittables/unzipped/terminal_velocity_tables_licensed
unzip -q data/gittables/src_zip/terminus_ad_quem_tables_licensed.zip -d data/gittables/unzipped/terminus_ad_quem_tables_licensed
unzip -q data/gittables/src_zip/then_tables_licensed.zip -d data/gittables/unzipped/then_tables_licensed
unzip -q data/gittables/src_zip/thing_tables_licensed.zip -d data/gittables/unzipped/thing_tables_licensed
unzip -q data/gittables/src_zip/time_interval_tables_licensed.zip -d data/gittables/unzipped/time_interval_tables_licensed
unzip -q data/gittables/src_zip/time_out_tables_licensed.zip -d data/gittables/unzipped/time_out_tables_licensed
unzip -q data/gittables/src_zip/time_slot_tables_licensed.zip -d data/gittables/unzipped/time_slot_tables_licensed
unzip -q data/gittables/src_zip/track-to -d data/gittables/unzipped/track-track_seek_time_tables_licensed.zip
unzip -q data/gittables/src_zip/usance_tables_licensed.zip -d data/gittables/unzipped/usance_tables_licensed
unzip -q data/gittables/src_zip/wartime_tables_licensed.zip -d data/gittables/unzipped/wartime_tables_licensed
unzip -q data/gittables/src_zip/whole_tables_licensed.zip -d data/gittables/unzipped/whole_tables_licensed
